### PR TITLE
Add padding option

### LINKED ISSUE #5: Avoid adding .0
What do you think about a boolean `padding` option to decide whether to keep the specified precision or round it when possible?

```ts
interface Options {
  padding: boolean = true,
  symbols: Array<string> = ["", "K", "M", "G", "T", "P", "E"],
}
```

```js
abbreviateNumber(1/4, 3) // => '1.250'
abbreviateNumber(1/4, 3, {padding: false}) // => '1.25'
```

### PR DESCRIPTION
**Pull request by fregante**
Closes #5 

- [x] Add tests
- [x] Add documentation

### CODE REVIEW

**Comment by moh3n9595** [comment]
v1.1.0 is out, thanks @fregante !

**Comment by yakov116** [comment]
@moh3n9595 something went wrong in the publish I do not see any changes in V1.1.0

**Comment by fregante** [comment]
Indeed: https://www.unpkg.com/browse/js-abbreviation-number@1.1.0/dist/index.js

**Comment by moh3n9595** [comment]
@fregante, Seems the issue has been resolved in v1.1.2.
Check this out.

**Comment by fregante** [comment]
Yes! Thank you!

**Pull request merged**
